In [1]:
import numpy as np

In [2]:
s=np.random.randn(2,3)

In [3]:
s

array([[-1.50569245,  0.21803068, -0.1311472 ],
       [-0.61518695,  0.36546358,  1.18972236]])

In [4]:
s*10

array([[-15.05692453,   2.18030682,  -1.31147202],
       [ -6.15186949,   3.65463579,  11.8972236 ]])

In [5]:
s[0,1]*4

0.8721227275675657

In [6]:
s.dtype

dtype('float64')

In [7]:
s.shape

(2, 3)

In [8]:
s.ndim

2

In [9]:
data=[5,2,4]
arr=np.array(data)
print(arr)

[5 2 4]


In [10]:
data1=[[1,2,3],[6,7,8]]
arr1=np.array(data1)
print(arr1)

[[1 2 3]
 [6 7 8]]


In [11]:
arr1.shape


(2, 3)

In [12]:
arr1.dtype


dtype('int32')

In [13]:
arr1.ndim

2

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 3.1.23 basic indexing and slicing

In [15]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr1=np.array([1,2,3])

In [18]:
arr1

array([1, 2, 3])

In [19]:
arr1.dtype

dtype('int32')

In [20]:
arr1.astype(np.float64)

array([1., 2., 3.])

In [21]:
ar=np.array([3.5,5.6,-0.5,0.2,-5.6,1.4])
ar

array([ 3.5,  5.6, -0.5,  0.2, -5.6,  1.4])

In [22]:
ar.astype(np.int32)

array([ 3,  5,  0,  0, -5,  1])

In [23]:
ars=np.array(['1.23','-0.98','42'],dtype=np.string_)
ars

array([b'1.23', b'-0.98', b'42'], dtype='|S5')

In [24]:
arrr=np.array([[1,2,3],[4,5,6]])

In [25]:
arrr

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
#by using group operations we can do logical and arithmetic operations
#multiplication
arrr*arrr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [27]:
#division
1/arrr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [28]:
arr2=np.array([[0,-2.5,6],[-5.6,30,3.26]])
arr2

array([[ 0.  , -2.5 ,  6.  ],
       [-5.6 , 30.  ,  3.26]])

In [29]:
#logical
arr2>arrr

array([[False, False,  True],
       [False,  True, False]])

# 4.1.23

In [105]:
#boolean indexing
import numpy as np
names=np.array(['rolex','hari','jeni','dini','rolex','jeni','jeni','jeni','rolex'])
names

array(['rolex', 'hari', 'jeni', 'dini', 'rolex', 'jeni', 'jeni', 'jeni',
       'rolex'], dtype='<U5')

In [106]:
data=np.array([[0],[1],[2],[3],[4],[5],[6],[7],[8]])
data

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [107]:
names=='jeni'

array([False, False,  True, False, False,  True,  True,  True, False])

In [108]:
data[names=='jeni']

array([[2],
       [5],
       [6],
       [7]])

In [109]:
data[~(names=='jeni')]

array([[0],
       [1],
       [3],
       [4],
       [8]])

In [110]:
data[names!='jeni']

array([[0],
       [1],
       [3],
       [4],
       [8]])

In [111]:
data[names=='jeni',1:]

array([], shape=(4, 0), dtype=int32)

In [112]:
data[names=='jeni',:1]

array([[2],
       [5],
       [6],
       [7]])

In [113]:
mask=(names=='jeni')|(names=='rolex')
mask

array([ True, False,  True, False,  True,  True,  True,  True,  True])

In [39]:
data[mask]
data

array([[-0.40895888],
       [-0.79745238],
       [ 1.99459562],
       [ 0.6696223 ],
       [ 0.52988283],
       [ 0.98714508],
       [ 1.76092569],
       [-0.07529143],
       [-0.76820947]])

In [114]:
data[data<5]=1
data

array([[1],
       [1],
       [1],
       [1],
       [1],
       [5],
       [6],
       [7],
       [8]])

In [74]:
data[names=='jeni']=7
data

array([[0],
       [1],
       [7],
       [3],
       [4],
       [7],
       [7],
       [7],
       [8]])

### 5-1-21

In [118]:
#fancy indexing
import numpy as np

In [119]:
arr=np.empty([8,4])
arr.dtype

dtype('float64')

In [120]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [121]:
for i in range(8):
    arr[i]=i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [122]:
arr[[4,3,0]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.]])

In [47]:
arr[[4,3,0],[3,0,2]]

array([4., 3., 0.])

In [131]:
arr=np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [132]:
arr[[4,3,0],[3,0,2]]

array([19, 12,  2])

In [133]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [135]:
arr[2:5,:]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])