In [1]:
#SWETHA JENIFER S_225229142

In [2]:
import numpy as np

In [3]:
wines = np.genfromtxt("winequality-red.csv", delimiter=";", skip_header=1)

##### NUMPY AGGREGATION METHODS

In [4]:
#sum of all residual sugar values
sum(wines[:,3])

4059.550000000003

In [5]:
#sums of every feature value. There are 12 features altogether
sum(wines)

array([13303.1    ,   843.985  ,   433.29   ,  4059.55   ,   139.859  ,
       25384.     , 74302.     ,  1593.79794,  5294.47   ,  1052.38   ,
       16666.35   ,  9012.     ])

In [6]:
#Find sum of every row
wines[:,:].sum(axis=1)

array([ 74.5438 , 123.0548 ,  99.699  , ..., 100.48174, 105.21547,
        92.49249])

In [7]:
#What is its size?
wines.shape[0]

1599

In [8]:
#What is its size?
wines.shape

(1599, 12)

In [9]:
# convert sugar value into int data type first
a=wines[:,3]
b=a.astype('int32')
b

array([1, 2, 2, ..., 2, 2, 3])

In [10]:
#the maximum residual sugar value in red wines data?
max(b)

15

In [11]:
#the minimum residual sugar value in red wines data
min(b)

0

In [12]:
#the average residual sugar value in red wines data
np.mean(a)

2.53880550343965

In [13]:
#25 percentile residual sugar value
np.percentile(a,25)

1.9

In [14]:
#75 percentile residual sugar value
np.percentile(a,75)

2.6

In [15]:
#the average of each feature value
wines[:,:].mean(axis=0)

array([ 8.31963727,  0.52782051,  0.27097561,  2.5388055 ,  0.08746654,
       15.87492183, 46.46779237,  0.99674668,  3.3111132 ,  0.65814884,
       10.42298311,  5.63602251])

#### NumPy Array Comparisons

In [16]:
#Show all wines with quality > 5
wines[:,11]>5

array([False, False, False, ...,  True, False,  True])

In [17]:
#Show all wines with quality > 7
j=wines[:,11]>7
j

array([False, False, False, ..., False, False, False])

In [18]:
#check if any wines value is True for the condition quality > 7
True in j

True

In [19]:
#Show first 3 rows where wine quality > 7, call it high_quality
high_quality=j
high_quality

array([False, False, False, ..., False, False, False])

In [20]:
#Show only top 3 rows and all columns of high_quality wines data
wines[high_quality][:3]

array([[7.900e+00, 3.500e-01, 4.600e-01, 3.600e+00, 7.800e-02, 1.500e+01,
        3.700e+01, 9.973e-01, 3.350e+00, 8.600e-01, 1.280e+01, 8.000e+00],
       [1.030e+01, 3.200e-01, 4.500e-01, 6.400e+00, 7.300e-02, 5.000e+00,
        1.300e+01, 9.976e-01, 3.230e+00, 8.200e-01, 1.260e+01, 8.000e+00],
       [5.600e+00, 8.500e-01, 5.000e-02, 1.400e+00, 4.500e-02, 1.200e+01,
        8.800e+01, 9.924e-01, 3.560e+00, 8.200e-01, 1.290e+01, 8.000e+00]])

In [21]:
#Show wines with a lot of alcohol > 10 and high wine quality > 7
er=(wines[:,10]>10)&(wines[:,11]>7)
er

array([False, False, False, ..., False, False, False])

In [22]:
#show only alcohol and wine quality columns
wines[er,10:]

array([[12.8,  8. ],
       [12.6,  8. ],
       [12.9,  8. ],
       [13.4,  8. ],
       [11.7,  8. ],
       [11. ,  8. ],
       [11. ,  8. ],
       [14. ,  8. ],
       [12.7,  8. ],
       [12.5,  8. ],
       [11.8,  8. ],
       [13.1,  8. ],
       [11.7,  8. ],
       [14. ,  8. ],
       [11.3,  8. ],
       [11.4,  8. ]])

### Combining NumPy Arrays

In [23]:
#Combine red wine and white wine data
#Open white wine dataset

In [24]:
white_wines=np.genfromtxt("winequality-white.csv",delimiter=";",skip_header=1)

In [25]:
#Show size of white_wines
white_wines.size

58776

In [26]:
white_wines.shape

(4898, 12)

In [27]:
#combine wines and white_wines data frames using vstack and call it all_wines
all_wines=np.vstack((wines,white_wines))

In [28]:
#what is size of all wines
all_wines.shape

(6497, 12)

In [29]:
#Combine wines and white_wines data frames using concatenate method
all_wines1=np.concatenate((wines,white_wines),axis=0)

In [30]:
#size of data2
all_wines1.size

77964

### Matrix Operations and Reshape

In [31]:
#Find Transpose of wines and print its size
tran=wines.T
tran.shape

(12, 1599)

In [32]:
#Convert wines data into 1D array
wines.ravel()

array([ 7.4 ,  0.7 ,  0.  , ...,  0.66, 11.  ,  6.  ])

In [33]:
#show size
wines.ravel().shape

(19188,)

In [34]:
#Reshape second row of wines into a 2-dimensional array with 2 rows and 6 columns
wines[1].reshape((2,6))

array([[ 7.8   ,  0.88  ,  0.    ,  2.6   ,  0.098 , 25.    ],
       [67.    ,  0.9968,  3.2   ,  0.68  ,  9.8   ,  5.    ]])

In [35]:
#Sort alcohol column Ascending Order
sorted_alcohol=np.sort(wines[:,-2])

In [36]:
sorted_alcohol

array([ 8.4,  8.4,  8.5, ..., 14. , 14. , 14.9])

In [37]:
#Make sorting to take place in-place
wines[:,-2].sort()

In [38]:
#Show top 10 rows
wines[:,-2]

array([ 8.4,  8.4,  8.5, ..., 14. , 14. , 14.9])

In [39]:
#Sort alcohol column Descending Order
sorted_alcohol_desc=np.sort(wines[:,10])[::-1]

In [40]:
sorted_alcohol_desc

array([14.9, 14. , 14. , ...,  8.5,  8.4,  8.4])

In [41]:
#sorted_alcohol_desc=np.sort(wines[:,10])[::-1]
wines[:,-2]

array([ 8.4,  8.4,  8.5, ..., 14. , 14. , 14.9])