# NumPy Basics: Arrays and Vectorized Computation

In [1]:
import numpy as np

## The NumPy ndarray: A Multidimensional Array Object

In [2]:
import numpy as np
# Generate some random data
data = np.random.randn(2, 3)
data

array([[ 0.19411543, -1.31789801,  0.32033792],
       [-2.20884101,  0.74809282, -0.39931471]])

In [6]:
a=data * 10

In [7]:
a+10

array([[ 11.94115426,  -3.17898005,  13.20337924],
       [-12.08841015,  17.48092821,   6.00685294]])

In [4]:
data-10

array([[ -9.80588457, -11.31789801,  -9.67966208],
       [-12.20884101,  -9.25190718, -10.39931471]])

In [5]:
data-data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
data + data

array([[-0.4094,  0.9579, -1.0389],
       [-1.1115,  3.9316,  2.7868]])

In [7]:
data.shape

(2, 3)

In [8]:
data.size

6

In [9]:
data.ndim

2

In [8]:
data.dtype

dtype('float64')

### Creating ndarrays

In [34]:
d=np.array([4,5,7])
d

array([4, 5, 7])

In [35]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [36]:
arr1.ndim

1

In [37]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
arr2.ndim

2

In [39]:
arr2.shape

(2, 4)

In [40]:
arr1.dtype

dtype('float64')

In [41]:
arr2.dtype

dtype('int32')

In [42]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [45]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [48]:
np.empty((6,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [46]:
np.empty((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [47]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [49]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Data Types for ndarrays

In [65]:
arr1 = np.array([1.8, 2, 3], dtype=np.int32)
arr1.dtype

dtype('int32')

In [66]:
arr1

array([1, 2, 3])

In [67]:
a=arr1.astype(float)

In [68]:
a

array([1., 2., 3.])

In [69]:
arr1

array([1, 2, 3])

In [20]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2.dtype

dtype('int32')

In [21]:
arr2

array([1, 2, 3])

In [22]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [23]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [24]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [70]:
num = np.array(['1.25', '-9.6', '42'])
num.dtype

dtype('<U4')

In [71]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.dtype

dtype('S4')

In [25]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [26]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [72]:
empty_uint32 = np.empty(8)
empty_uint32

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 7.17383318e-321, 1.24610723e-306, 1.29061142e-306])

In [74]:
empty_uint32 = np.empty(8, dtype=np.int32)
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248])

In [75]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

### Arithmetic with NumPy Arrays

In [28]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr
arr * arr
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
1 / arr
arr ** 0.5

array([[1.    , 1.4142, 1.7321],
       [2.    , 2.2361, 2.4495]])

In [30]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [95]:
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
arr[5]


5

In [97]:
arr[5:8]


array([5, 6, 7])

In [98]:
arr[5:8] = 12

In [99]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [100]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [101]:
arr[6]=12345

In [102]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [103]:
arr_slice[1] = 12345
arr_slice

array([   12, 12345,    12])

In [104]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [105]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [107]:
arr2d[0][2]


3

In [108]:
arr2d[0, 2]

3

In [122]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [123]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [125]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [127]:
arr3d[1, 0]

array([7, 8, 9])

In [128]:
x = arr3d[1]
x
x[0]

array([7, 8, 9])

#### Indexing with slices

In [129]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [42]:
arr
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [130]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [131]:
arr2d
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [132]:
arr2d[2:]

array([[7, 8, 9]])

In [44]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [45]:
arr2d[1, :2]

array([4, 5])

In [46]:
arr2d[:2, 2]

array([3, 6])

In [47]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [48]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [133]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names


array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [134]:
data

array([[ 0.45289746, -1.52819989, -0.29012294, -0.07923784],
       [-0.17606029,  0.15999986,  0.00326045,  0.25143376],
       [-0.13420244, -1.05553526,  0.47290875, -0.26940867],
       [-1.14713835,  2.14662178, -0.07385833, -0.62039873],
       [ 0.09634713,  1.68864088, -0.34177153, -0.7495702 ],
       [-0.37301514,  0.20332043,  0.61611642, -0.7694056 ],
       [ 1.80369835,  0.43682513,  1.16447293, -0.56040024]])

In [135]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [136]:
data[names == 'Bob']

array([[ 0.45289746, -1.52819989, -0.29012294, -0.07923784],
       [-1.14713835,  2.14662178, -0.07385833, -0.62039873]])

In [139]:
data[names == 'Bob', 2:]


array([[-0.29012294, -0.07923784],
       [-0.07385833, -0.62039873]])

In [140]:
data[names == 'Bob', 3]

array([-0.07923784, -0.62039873])

In [142]:
names != 'Bob'


array([False,  True,  True, False,  True,  True,  True])

In [143]:
data[~(names == 'Bob')]

array([[-0.17606029,  0.15999986,  0.00326045,  0.25143376],
       [-0.13420244, -1.05553526,  0.47290875, -0.26940867],
       [ 0.09634713,  1.68864088, -0.34177153, -0.7495702 ],
       [-0.37301514,  0.20332043,  0.61611642, -0.7694056 ],
       [ 1.80369835,  0.43682513,  1.16447293, -0.56040024]])

In [144]:
cond = names == 'Bob'
cond

array([ True, False, False,  True, False, False, False])

In [145]:
data[~cond]

array([[-0.17606029,  0.15999986,  0.00326045,  0.25143376],
       [-0.13420244, -1.05553526,  0.47290875, -0.26940867],
       [ 0.09634713,  1.68864088, -0.34177153, -0.7495702 ],
       [-0.37301514,  0.20332043,  0.61611642, -0.7694056 ],
       [ 1.80369835,  0.43682513,  1.16447293, -0.56040024]])

In [162]:
mask = (names == 'Bob') & (names == 'Will')
mask

array([False, False, False, False, False, False, False])

In [163]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [149]:
data[mask]

array([[ 0.45289746, -1.52819989, -0.29012294, -0.07923784],
       [-0.13420244, -1.05553526,  0.47290875, -0.26940867],
       [-1.14713835,  2.14662178, -0.07385833, -0.62039873],
       [ 0.09634713,  1.68864088, -0.34177153, -0.7495702 ]])

In [150]:
data[data < 0] = 0
data

array([[0.45289746, 0.        , 0.        , 0.        ],
       [0.        , 0.15999986, 0.00326045, 0.25143376],
       [0.        , 0.        , 0.47290875, 0.        ],
       [0.        , 2.14662178, 0.        , 0.        ],
       [0.09634713, 1.68864088, 0.        , 0.        ],
       [0.        , 0.20332043, 0.61611642, 0.        ],
       [1.80369835, 0.43682513, 1.16447293, 0.        ]])

In [151]:
data[names != 'Joe'] = 7
data

array([[7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [0.00000000e+00, 1.59999857e-01, 3.26045201e-03, 2.51433757e-01],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [0.00000000e+00, 2.03320426e-01, 6.16116419e-01, 0.00000000e+00],
       [1.80369835e+00, 4.36825132e-01, 1.16447293e+00, 0.00000000e+00]])

### Fancy Indexing

In [159]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [59]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [60]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [165]:
arr = np.arange(32).reshape((8, 4))
arr


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [166]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [62]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Transposing Arrays and Swapping Axes

In [197]:
arr = np.arange(15).reshape((3, 5))
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [199]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [172]:
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [187]:
arr = np.arange(16).reshape((2, 2, 4))
arr
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [192]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [193]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [194]:
arr
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## Universal Functions: Fast Element-Wise Array Functions

In [205]:
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [207]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [208]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [210]:
x = np.random.randn(8)
y = np.random.randn(8)


In [211]:
x


array([-0.27129511, -0.3406275 , -0.39248588, -0.78415635, -0.01140995,
        0.85576503,  0.90380831, -0.01155488])

In [212]:
y


array([ 0.19277269,  0.58461663,  1.11561259,  0.82267793, -0.17072777,
        0.85206974,  2.22218835, -0.646708  ])

In [213]:
np.maximum(x, y)

array([ 0.19277269,  0.58461663,  1.11561259,  0.82267793, -0.01140995,
        0.85576503,  2.22218835, -0.01155488])

In [214]:
arr = np.random.randn(7) * 5
arr


array([13.73324688,  1.44494635, -2.54314835,  1.09825506, -2.43223319,
        5.99752059,  1.65174034])

In [216]:
remainder, whole_part = np.modf(arr)
remainder


array([ 0.73324688,  0.44494635, -0.54314835,  0.09825506, -0.43223319,
        0.99752059,  0.65174034])

In [217]:
whole_part

array([13.,  1., -2.,  1., -2.,  5.,  1.])

In [218]:
arr
np.sqrt(arr)
np.sqrt(arr, arr)
arr

C:\Users\sweth\AppData\Local\Temp\ipykernel_5452\2118003981.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)
C:\Users\sweth\AppData\Local\Temp\ipykernel_5452\2118003981.py:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([3.70583957, 1.20205921,        nan, 1.04797665,        nan,
       2.44898358, 1.28520051])

### Expressing Conditional Logic as Array Operations

In [221]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [223]:
result = [(x if c else y)
          for y,x, c in zip(yarr, xarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [226]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [227]:
arr = np.random.randn(4, 4)
arr


array([[-0.51219534, -2.82673585,  1.80494218, -1.0722401 ],
       [ 0.88821476, -0.09215784,  0.3617098 , -0.5437427 ],
       [ 0.17786414, -1.42108624, -0.90419498, -0.86458547],
       [ 0.3142906 ,  1.78194782, -0.27684049, -1.17030717]])

In [228]:
arr > 0
np.where(arr > 0, 2, -2)

array([[-2, -2,  2, -2],
       [ 2, -2,  2, -2],
       [ 2, -2, -2, -2],
       [ 2,  2, -2, -2]])

In [229]:
np.where(arr > 0, 2, arr) # set only positive values to 2

array([[-0.51219534, -2.82673585,  2.        , -1.0722401 ],
       [ 2.        , -0.09215784,  2.        , -0.5437427 ],
       [ 2.        , -1.42108624, -0.90419498, -0.86458547],
       [ 2.        ,  2.        , -0.27684049, -1.17030717]])

### Mathematical and Statistical Methods

In [236]:

arr=np.arange(4).reshape(2,2)
arr

array([[0, 1],
       [2, 3]])

In [237]:
arr.mean()


1.5

In [238]:
np.mean(arr)


1.5

In [239]:
arr.sum()

6

In [241]:
arr.mean(axis=1)

array([0.5, 2.5])

In [242]:
arr.sum(axis=0)

array([2, 4])

In [83]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [244]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [245]:
arr.cumsum(axis=0)


array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [246]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

### Methods for Boolean Arrays

In [250]:
arr = np.random.randn(100)
(arr > 0).sum() # Number of positive values

51

In [257]:
bools = np.array([True,True])
bools

array([ True,  True])

In [258]:
bools.any()


True

In [259]:
bools.all()

True

### Sorting

In [260]:
arr = np.random.randn(6)
arr


array([ 1.16056311,  0.37358699, -0.52803464,  0.29154766,  0.53655647,
       -0.10169918])

In [261]:
arr.sort()
arr

array([-0.52803464, -0.10169918,  0.29154766,  0.37358699,  0.53655647,
        1.16056311])

In [262]:
arr = np.random.randn(5, 3)
arr


array([[-0.52580349, -0.19988308, -0.59581249],
       [ 1.36899057,  0.45969257, -1.21071941],
       [ 1.48590144, -0.92797767, -0.65033251],
       [-0.35453572, -1.27920369,  0.24463608],
       [-0.10576051, -1.96563978, -0.75458236]])

In [263]:
arr.sort(1)
arr

array([[-0.59581249, -0.52580349, -0.19988308],
       [-1.21071941,  0.45969257,  1.36899057],
       [-0.92797767, -0.65033251,  1.48590144],
       [-1.27920369, -0.35453572,  0.24463608],
       [-1.96563978, -0.75458236, -0.10576051]])

In [89]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5% quantile

-1.5311513550102103

### Unique and Other Set Logic

In [266]:
names = np.array(['Bob',  'Will','Joe', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)


array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [267]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [269]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [92]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])